apiVersion: v1
kind: Service
metadata:
  name: {{ include "jellyfin.fullname" . }}
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.ip }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8096
      protocol: TCP
      name: jellyfin-web
    - port: 7359
      targetPort: 7359
      protocol: TCP
      name: jellyfin-discovery
    - port: 1900
      targetPort: 1900
      protocol: TCP
      name: jellyfin-dlna
  selector:
    {{- include "jellyfin.selectorLabels" . | nindent 4 }}
